name: docker build

# 1. Trigger
on:
  push:
    branches:
      - main

jobs:
  main:
    env:
      IMAGE_NAME: co2-checker
    runs-on: ubuntu-latest
    steps:
    # 3. Checkout code
    - name: Checkout
      uses: actions/checkout@v2
    # 5. setup buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    # 6. Build and Push
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GCR_PAT }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/v6
        push: true
        # 7. nameing
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
