name: docker build

# 1. Trigger
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    # 3. Checkout code
    - name: Checkout
      uses: actions/checkout@v2
    # 5. setup buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    # 6. Build and Push
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm/v7,linux/v6
        push: false
        # # 7. nameing
        # tags: |
        #   ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CI_REPOSITORY_NAME }}:latest
